# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "2.68.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "7e7d86ca-1926-42be-93c6-6bde7503bcbd"

default_platform :android

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later
lane :beta do
  # build the release variant
  build_android_app(task: "assembleRelease")

  # upload to Beta by Crashlytics
  crashlytics(
    api_token: "cbe7680d1c986532833d98dc1134f52925897f2e",
    build_secret: "69f550a742ab1b64ec1232de756ff8c595e5a3a6e5e1743825bbaa6d0293efbd"
  )

  # slack(
  #   slack_url: "https://hooks.slack.com/services/IDS"
  # )
end
